### ISSUE TITLE
Doc Navigation Faulty

### ISSUE THREAD

**Issue by therealkitman** [rorywalsh/cabbage#1]
When trying to navigate the newly built Docs (file:///home/chris/Downloads/git/cabaiste_audio_graph/Docs/_book/index.html), the left hand side index does not work for me in Firefox 51.

The browser's Inspector shows an issue with a missing </link> tag.

![image](https://cloud.githubusercontent.com/assets/14888092/23575718/de3dbe88-00cc-11e7-8d6a-194fd87ae22f.png)

I can manually open each document in the meantime via my file browser.

**Comment by rorywalsh** [comment]
Thanks. I haven't even tried building the docs using the new repo. It was just copied over from the last. I have been updating them when needed however. I'll take a look at building them shortly. In the meantime, you can find an online version of the docs [here](http://cabbageaudio.com/docs/introduction/).

**Comment by rorywalsh** [comment]
The docs system has been completely updated. The most up to date docs an be found `[here](http://cabbageaudio.com/beta/CabbageManual.zip)`:
