### ISSUE TITLE
Crash if no file is loaded into view

### ISSUE THREAD

**Issue by muziker** [rorywalsh/cabbage#112]
For Cabbage 2.5.24, according to the about dialog. v2.5.0-168-gc041e155 according to git describe --tags. 

Cabbage crashes if select item in the drop down box at the menu bar, and no file is being shown. Eg.

1. Load a csd into cabbage
2. hit X to remove the file in the tab just under the menu bar
3. In the drop down box where the user can select the position in the file to jump to, select an item
4. crash !

**Comment by rorywalsh** [comment]
Thanks, I have this fixed now. I will push to git a little later. I have another few issues to see to first.
