### ISSUE TITLE
Cabbage crashes if csd file has no cabbage section 

### ISSUE THREAD

**Issue by muziker** [rorywalsh/cabbage#113]
For Cabbage 2.5.24, if the csd file does not contain a Cabbage start and end tags, when the tab is played, a popup warns about needing enclosing cabbage tags, then cabbage dies.

**Comment by rorywalsh** [comment]
Good spot. I've pushed a fix for this, and added a 'don't show warning in future' option to the message dialogue that appears. I guess if you are using Cabbage as a straight-up Csound editor this warning could get very annoying! Maybe you can test, and close this out if you are happy that it passes ;)
