### ISSUE TITLE
Simple documentation error - Opcode Page

### ISSUE THREAD

**Issue by russellcameronthomas** [rorywalsh/cabbage#114]
On the last code example on the Opcode page (https://cabbageaudio.com/docs/opcodes/),  I believe "a3" should be "a2"

<img width="852" alt="Cabbage Doc Error" src="https://user-images.githubusercontent.com/11158109/116329073-784b4b00-a798-11eb-8bb8-0398a2fe1a5f.png">

**Comment by rorywalsh** [comment]
Fixed in git. I'll push out new docs in the next big point release, which I hope should in the next week or two.
