### ISSUE TITLE
Suggestion:  allow fractional mouse wheel parameter in "Settings"; also font size

### ISSUE THREAD

**Issue by russellcameronthomas** [rorywalsh/cabbage#115]
I use an iMac 27" and an Apple magic mouse 2.  

Problem: the scrolling in the Code Window is *very* twitchy.  I don't experience this problem in any other software or app.

I tried setting the scroll parameter to "0.5" but it truncated to "0" so I got no scrolling.  It seems to only allow integers.

Can you allow fractional parameters?

Also: can you add an option to change font size?  This would have a side effect of reducing the "twitching scroll problem" because the line sizes would be bigger.

Thanks

**Comment by rorywalsh** [comment]
Hi @russellcameronthomas You can change the font size using teh Zoom in/out menu commands, of CMD+[ on a Mac, or Ctrl+[ on a PC. I will update the menu command label to mention font. It's not very clear. 

I'm afraid that there is no option for fractional jumps as the underlying methods only accepts integer values. I hope that changing the font size can help.

**Comment by russellcameronthomas** [comment]
I will try Zoom and hope that works.  Thanks.

**Comment by russellcameronthomas** [comment]
Zoom works well to make the font larger in the edit box, and the twitchy scroll problem has gone away.

Maybe you could add "Zoom..." to the "View" menu, like some other applications do.

**Comment by rorywalsh** [comment]
Done. As of version 2.6.6 you should be able to control zooming in and out from the view menu too.
