### ISSUE TITLE
Cabbage 2.6 does not run in Pop!_OS 20.10

### ISSUE THREAD

**Issue by benrogmans** [rorywalsh/cabbage#116]
Steps to reproduce on a fresh install of Pop!_OS 20.10 (Ubuntu based distro):

1. Download Cabbage 2.6 from here: https://github.com/rorywalsh/cabbage/releases/download/v2.6.0/Cabbage-2.6-DEB.zip
2. Run `sudo ./installCabbage`
3. Run `/usr/bin/Cabbage`

Output:
`/usr/bin/Cabbage: symbol lookup error: /usr/bin/Cabbage: undefined symbol: csoundLoadPlugins`

**Comment by rorywalsh** [comment]
Cabbage uses the latest version of Csound. You'll need to build it yourself as I don't think the latest Deb package are up to date. Let me know how it goes.

**Comment by benrogmans** [comment]
This worked, thank you!

Sorry for the late reply - I was away from my linux machine for a few days.
