### ISSUE TITLE
Possibility to build from CLI?

### ISSUE THREAD

**Issue by thomas-alrek** [rorywalsh/cabbage#120]
Is it possible to export a VST/AU from the command line? It would be interesting for me to use Cabbage in a CI pipeline, where I can build my plugin, and automatically export the plugins in a headless setup.

**Comment by rorywalsh** [comment]
You can try

`Cabbage --export-VST myfile.csd`

This is one of those things I added before for a user, but I'm not sure it was ever properly tested. Let me know how you get on. Btw, just a heads up, but you'll get me much quicker over on the Cabbage forum. You can sign in their with your github credentials. No need to register anew.

**Comment by thomas-alrek** [comment]
Thanks, that seems to work! I am checkout out the forums now.
