### ISSUE TITLE
Cabbage closes without any message

### ISSUE THREAD

**Issue by christianmalek** [rorywalsh/cabbage#130]
Hey!

If I don't have any file open and press any of these buttons (see screenshot) Cabbage just closes without any message.

![grafik](https://user-images.githubusercontent.com/2873986/149199533-1ac231b0-858d-4e4b-aa75-20810770d51a.png)

**Comment by rorywalsh** [comment]
Thanks @christianmalek I just pushed a fix for this :+1:
