### ISSUE TITLE
Possible to install on Linux Fedora 36?

### ISSUE THREAD

**Issue by poulpoulsen** [rorywalsh/cabbage#134]
Hello,
i want to use Cabbage on Fedora 36. But i can only find a deb package.
the other way (building from source), seems not to work, because the requirements-script seems to work with apt. Fedora use dnf as installer.
any ideas?

Regards
Poul

**Comment by rorywalsh** [comment]
Hmm, good question. I think if you can build Csound, and have a go at building the JUCE demo application from source you should be able to build Cabbage. Sorry, I'm on vacation at the moment but will be back in a week or so. I may be able to better advise then 👍

**Comment by poulpoulsen** [comment]
ok, i will wait.
happy vacation!

**Comment by rorywalsh** [comment]
Did you resolve this?

**Comment by rorywalsh** [comment]
Closing this out - no response
