### ISSUE TITLE
stop setting CWD...

### ISSUE THREAD

**Issue by rorywalsh** [rorywalsh/cabbage#136]
This causes issues with certain hosts and is should be avoided where possible..

**Comment by TartanLlama** [comment]
Looking into getting ComboBoxes working without setting CWD atm. One issue is that CSound instructions like compileorc seem to rely on this (not sure if this is default behaviour or something which Cabbage does), so sending relative paths to them breaks. Users could handle this in their CSound code, but maybe you know of a better way?

**Comment by rorywalsh** [comment]
Csound typically uses the .csd location as the root dir unless otherwise specified. The issue I've seen in the past is that certain hosts will change CWD, which is why I resorted to changing it back. I guess the most robust way would be to handle this in Csound code. There is a reserved channel call CSD_PATH that will return the location of the current csd file. This could be used to create the correct paths to other assets. It might mean a bit of a rewriting in Lore though..

**Comment by TartanLlama** [comment]
Yeah, that's what I ended up doing, was just a couple lines!

**Comment by rorywalsh** [comment]
This has been addressed. Cabbage no longer sets CWD
