### ISSUE TITLE
Installation not work on linux manjaro distro based

### ISSUE THREAD

**Issue by lucas-r-leite** [rorywalsh/cabbage#142]
Hello, 

I followed the tutorial for build and install cabbage on Linux. I think the build was a sucess, because of the Installers directory. But when I try to install, by following the comands, this log errors appears: 

installing ../../CabbageInstall/images/cabbage.png to /usr/share/icons/hicolor/512x512/apps
install: não foi possível obter estado de '../../CabbageInstall/bin/*': Arquivo ou diretório inexistente
installing ../../CabbageInstall/bin/* to /usr/bin
install: não foi possível obter estado de '../../CabbageInstall/desktop/*': Arquivo ou diretório inexistente
installing ../../CabbageInstall/desktop/* to /usr/share/applications
installing VST3 effect interface to /usr/bin/CabbagePluginEffect.vst3
cp: não foi possível obter estado de '../../CabbageInstall/bin/CabbagePluginEffect.vst3': Arquivo ou diretório inexistente
installing VST3 effect interface to /usr/bin/CabbagePluginSynth.vst3
cp: não foi possível obter estado de '../../CabbageInstall/bin/CabbagePluginSynth.vst3': Arquivo ou diretório inexistente
installing Examples to /usr/share/doc/cabbage/Examples
installing CabbageManual to /usr/share/doc/cabbage/CabbageManual
installing CabbageRack to /usr/bin/CabbageRack
installing Themes to /usr/share/cabbage/Themes

**Comment by lucas-r-leite** [comment]
Yes

**Comment by lucas-r-leite** [comment]
That error log appears when I ran as sudo

**Comment by lucas-r-leite** [comment]
This log error appeared when I ran it as sudo

**Comment by lucas-r-leite** [comment]
I think the problem is because my system has directories in Português

**Comment by rorywalsh** [comment]
This could be the reason. You can edit the folders in this file https://github.com/rorywalsh/cabbage/blob/develop/Installers/Linux/installCabbage.sh
and try rerunning it. All the install directories are listed at the top.

**Comment by lucas-r-leite** [comment]
Thanks

**Comment by rorywalsh** [comment]
Let me know if that works :)

**Comment by lucas-r-leite** [comment]
Actually I came back to Windows10, so I can't test if it works or not. But I really appreciate your attention and support.

**Comment by lucas-r-leite** [comment]
PS.: But it's work just fine on Windows10.

**Comment by rorywalsh** [comment]
If you do ever get to modify the scripts on Linux let me know if it works out for you. Feel free to reopen this issue at a later date if you need to.
