### ISSUE TITLE
xypad doesn't update value display when automating via DAW

### ISSUE THREAD

**Issue by woutersnoei** [rorywalsh/cabbage#146]
Hi, I stumbled on a little issue with xypad; when I create an xypad in an AudioUnit plugin and try to automate it via a DAW's timeline (in my case; Logic) it does move the green ball, but the values displayed at the bottom of the widget don't change. They only change when I move the ball manually. This is probably a little bug where something doesn't update when it should, but I can't find exactly where it happens in the source code..

**Comment by rorywalsh** [comment]
I just checked the xypa example, and it doesn't update the labels either. That's a bug, I did some work on the xypad a few months ago, I must have scrambled the labels somehow. I'll take a look.

**Comment by woutersnoei** [comment]
Works like a charm, thanks!
