### ISSUE TITLE
Cabbage widget to show Csound console messages

### ISSUE THREAD

**Issue by gogins** [rorywalsh/cabbage#147]
I am requesting an addition to Cabbage, namely a new GUI widget that displays an automatically scrolling log of Csound's console message.

**Comment by rorywalsh** [comment]
What you're looking for is the [`csoundoutput`](https://cabbageaudio.com/docs/csound_output/) widget.

**Comment by gogins** [comment]
Did not know about that one either, thanks!

**Comment by rorywalsh** [comment]
No problem, I've got you covered 🤣

**Comment by gogins** [comment]
It works as you say -- except when playing a Reaper piece, sometimes audio
from Csound stops and is replaced by a whine.

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by rorywalsh** [comment]
A Reaper piece? You mean using a plugin in Reaper? I don't see how the console widget would cause Csound to break? Unless you're pushing huge amounts of messages to the console?

**Comment by gogins** [comment]
The console widget works fine, I'm sorry I didn't read the documentation fully.
