### ISSUE TITLE
cmake doesn't check for dependencies/ readme is hidden

### ISSUE THREAD

**Issue by ssj71** [rorywalsh/cabbage#15]
Hi:

I'm still on my quest to get hadron, but ran into a few hiccups. I'm on Ubuntu 15.10 with the kxstudio repos.

First compile error was because GL/gl.h wasn't found. I had to install mesa-common-dev to get around that.
Next was csound.hpp. I can't find it under any of the ubuntu packages, only the C header csound.h. I think this is the end of the road for me. I might have to wait until it lands in the kxstudio repos. I thought I'd report what I'd found though. Cmake could potentially check for these packages and warn me that I don't have them before I try to make.

Also the readme is devoid of any instructions now.

regardless of these issues I'm still impressed with what you've done around here! Thanks.

**Comment by ssj71** [comment]
Ah! the readme is in the Builds directory. I've never seen that before. Perhaps a hint in the root README would be helpful to others too.

**Comment by rorywalsh** [comment]
I'll add a note! Cheers. The CMake implementation was never completed but the makefiles in place run pretty well.
