### ISSUE TITLE
A few errors preventing Debian Linux 64 bit build

### ISSUE THREAD

**Issue by MrMormon** [rorywalsh/cabbage#16]
I just installed Debian Jessie's current g++, but that couldn't be it, right? Thank you.
```
buildCabbage "/usr/include/csound" "/usr/lib" ""
```
...
```
../../Source/Plugin/CabbagePluginProcessor.cpp:1546:82: error: ‘csoundGetTableArgs’ was not declared in this scope
         int noOfArgs = csoundGetTableArgs(csound->GetCsound(), &argsPtr, tableNum);
                                                                                  ^
```
...
```
../../JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.cpp:36:23: fatal error: AppConfig.h: No such file or directory
 #include "AppConfig.h"
                       ^
compilation terminated.
```

**Comment by rorywalsh** [comment]
csoundGetTableArgs() is a new API function found in Csound 6.03 and upwards. What version of Csound are you using, looks like an old one? Not exactly sure how you're getting the second compiler error, but let's sort the Csound issue first.

**Comment by MrMormon** [comment]
Whoops, you're probably right. Since Debian testing doesn't have this problem (and I'm not using the distro with these problems anymore), I'll just close this as not following instructions and Debian stable having a Csound old as heck.

Apologies for adding to the issue history and taking time.
