### ISSUE TITLE
Linux build incomplete

### ISSUE THREAD

**Issue by pabloriera** [rorywalsh/cabbage#3]
Hi I tried to build it in Ubuntu and it reaches to this point and exits.

```
Compiling CabbageMessageSystem.cpp
Linking CabbageHost
cp: cannot stat '../../Docs/_book': No such file or directory
```

If I execute the binary it starts but hangs when opening a file. I don't know what else information could be appropriate for debugging. 

Best,

**Comment by rorywalsh** [comment]
Looks like you are using some old source files. Make sure you are using the latest tip and try again. Follow the instructions here:
https://github.com/rorywalsh/cabbage/blob/master/Builds/LinuxMakefile/readme.md
