### ISSUE TITLE
Linux build broken without VST 2.x

### ISSUE THREAD

**Issue by SynthaClaus** [rorywalsh/cabbage#33]
Hi!

I can't get Cabbage to build on Linux because the VST 2.x SDK is no longer available from Steinberg or from anywhere else as far as I can tell. The needed file _pluginterfaces/vst2.x/aeffect.h_ is not included in the newer VST3_SDK, which is linked to in the readme.

Update: I found a link to an **older** version of the VST3 SDK which had the needed files:
[(https://www.steinberg.net/sdk_downloads/vstsdk366_27_06_2016_build_61.zip)]

Thx!

**Comment by rorywalsh** [comment]
It sucks that Steinberg have done this. I hope it results in more hosts offering VST3 support, but the jury is still out. Glad you got it sorted.

**Comment by SynthaClaus** [comment]
Actually, I haven't got it sorted yet. I have the VST3 SDK containing the needed files (pluginterface/aeffect.h), but I can't figure out there to put them so the _buildCabbage_ script finishes without error:

I have tried all combinations I could think of. The documentation (multiple readme files) suggest 
 to put the SDK in _~/SDKs/_ as well as _~/SDK/_  and I found a post from you suggesting to append the path (both with a space and an underscore) to the _buildCabbage_ command. I have tried copying all subfolders (VST3(_)SDK/, pluginterface/, vst2.x/) to aforementioned locations, but without success...

Could you please tell me which folder is supposed to be in which location?
Thanks once again!

Yours sincerely,
SynthaClaus

**Comment by rorywalsh** [comment]
Throw it into `~SDKs/VST3 SDK/pluginterfaces` so you will then have the following structure:
`~SDKs/VST3 SDK/pluginterfaces/vst2.x` That should do it.

**Comment by SynthaClaus** [comment]
Thanks, but it does not work. The following file is available:
_/home/[username]/SDKs/VST3 SDK/pluginterfaces/vst2.x/aeffect.h_

yet the build fails with:

> In file included from ../../JuceLibraryCode/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp:27:0,
                 from ../../JuceLibraryCode/include_juce_audio_plugin_client_VST2.cpp:9:
../../JuceLibraryCode/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:95:10: fatal error: pluginterfaces/vst2.x/aeffect.h: No such file or directory
 #include "pluginterfaces/vst2.x/aeffect.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
>
Cabbage is located in _.../cabbage-git/cabbage/_ and Juce in _../cabbage-git/JUCE/_.

Building CSound and Projucer went fine but I am afraid I am kinda stuck now...
Any ideas are welcome :)

**Comment by rorywalsh** [comment]
That's odd. Can you open the Projucer application and under the File menu select the Global Paths. Then make sure that the correct folders are set up:

![image](https://user-images.githubusercontent.com/2689817/50230095-df27f080-03a3-11e9-8a5a-51bc656f3221.png)

**Comment by rorywalsh** [comment]
Do you have aeffect.h, aeffectx.h and vstxstore.h in your vst2.x folder? I believe you need the 3 of those files?

**Comment by SynthaClaus** [comment]
Yes, and I have tried pointing to all possible folders in the _VST (Legacy) SDK_ and _VST3 SDK_ settings of Projucer (5.3.2 and 5.4.1), but they simply will not be found. Only when I hardcode the absolute path into _juse_VST_Wrapper.cpp_ (95/96) can I compile Cabbage.

**Comment by rorywalsh** [comment]
I will be doing some work with the Linux build in a few days. I'll look
into it and see if a better solution can be found.

**Comment by SynthaClaus** [comment]
Awesome! It would be cool if it were easier to start using it on Linux, since it's a great application.
