### ISSUE TITLE
Readme is empty

### ISSUE THREAD

**Issue by dromer** [rorywalsh/cabbage#4]
The website says ```There is a README outlining the necessary steps.```

The readme is nearly completely useless.
Any basic documentation available? :)

**Comment by rorywalsh** [comment]
For using Cabbage? Or building it? Using Cabbage:
http://cabbageaudio.com/docs/introduction/
http://cabbageaudio.com/tutorials/
Building depends on your OS, but browse the Builds folder of the source tree for details. Each source tree has a script that automates building which you might find useful. The Linux build tree has fairly decent instructions, the other don't, as I provide fairly regularly builds for Windows and OSX. Apropos, details on how to build for those OSs can be found the appveyor and travis scripts.

**Comment by dromer** [comment]
Thnx. I expected the main readme to contain at least 'some' information about any of it (development. build instructions. etc)

Running in to some issues building on linux, supposedly csound version (6.08).
I may open an issue separately if I pursue.

**Comment by rorywalsh** [comment]
Fair point. I'll update the readme ;)

**Comment by rorywalsh** [comment]
Btw, the build errors could be to do with JUCE 5.2.1, changing to 5.2.0 should fix them. I'll update the readme

**Comment by rorywalsh** [comment]
The README has been updated so I'm going to close this issue now. Feel free to reopen it if you feel it still warrants attention.
