### ISSUE TITLE
Support Juce 5.4.3 on Linux

### ISSUE THREAD

**Issue by hlolli** [rorywalsh/cabbage#42]
Jucer has seemingly new way of installing plugins via makefile. Seems to be incompatible with the current buildCabbage script.

**Comment by rorywalsh** [comment]
Thanks, I'm just about to update to 5.4.3. I'll take a look. I'm on Linux less these days so I'm happy to accept PRs..

**Comment by rorywalsh** [comment]
@hlolli can you make sure you're on the develop branch? I just did a fresh clone and it built without any issues.

**Comment by hlolli** [comment]
I'll take another look, I thought I tried it, will update

**Comment by hlolli** [comment]
This is what I'm currently getting from develop

```
===========================================
======== Build Script for Cabbage =========
===========================================
In order to build Cabbage you will need to have Csound installed, and
the Projucer from version 5.0 of JUCE built and installed.
This scripts assumes that Csound is installed in the default location, i.e, includes files
should be located in /user/local/include/csound while the Csound library itself should be
located in /user/local/lib
It is also assumes that the VST SDK is located in ~/SDKs/

buildCabbage: line 15: [: ==: unary operator expected
buildCabbage: line 37: ../../../JUCE/extras/Projucer/Builds/LinuxMakefile/build/Projucer: No such file or directory
```

juce and cabbage are siblings in the same parent directory.

**Comment by hlolli** [comment]
I don't know how you can have successfully built it because in the new Juce this LinuxMakefile directory doesn't exist, there's something like `/extras/Projucer/Builds/LinuxMakefile` there, but the directories look just different from what the build script expects.

**Comment by rorywalsh** [comment]
The 'build' directory is created when you successfully build the Projucer. You need to do that before you run the Cabbage build script. It's in the [readme](https://github.com/rorywalsh/cabbage/tree/master/Builds/LinuxMakefile) file. Also note that if you don't want to mess with paths, just make sure that the Cabbage root dir lives in the same directory as the JUCE root dir. Also note that you'll need the VST2 SDK to build the plugin interfaces..

**Comment by hlolli** [comment]
Sorry missed out that part of the readme :)

**Comment by hlolli** [comment]
Ok my goal is simply to make a nix build script to run Cabbage on NixOs. With some sed's and hacking I've been able to get far into the compilation. But now I'm stuck on

```
In file included from ../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.cpp:148:0,
                 from ../../JuceLibraryCode/include_juce_audio_processors.cpp:9:
../../JuceLibraryCode/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:49:10: fatal error: pluginterfaces/vst2.x/aeffect.h: No such file or directory
 #include <pluginterfaces/vst2.x/aeffect.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

On steinberg I downloaded both
```
VST 3 Audio Plug-Ins SDK (Format: zip, 80MB)

VST Module Architecture SDK (Format: zip, 0.35 MB)
```

but neither includes this file aeffect.h, but I do find audioeffect.h, so I wonder if Juce is expecting older version of VSD_SDK than steinberg is currently providing?

**Comment by rorywalsh** [comment]
Yes, on Linux Cabbage needs access to the VST2.4 SDK which is discontinued by Steinberg. Not only that, but they have removed all reference to it from their servers. Unless you have access to them I'm afraid you won't be able to build Cabbage...

**Comment by hlolli** [comment]
Ok, good to know.

Unrelated, I notice a quoteing error

this here is from a generated CabbagePlugin.juce file

```
-I"/usr/local/include/csound" -I"/usr/include/csound"$(HOME)/SDKs/VST_SDK/VST3_SDK" $(CPPFLAGS)
```

which gives me an error 

```
/bin/sh: syntax error: unterminated quoted string
```

my guess is that this needs to be rechecked

https://github.com/rorywalsh/cabbage/blob/develop/CabbagePlugin.jucer#L206-L211

I'll sed it to make it work, make a PR later :)

**Comment by rorywalsh** [comment]
I have that fixed now. I'll close out this issue. If you need to reopen feel free.
