### ISSUE TITLE
Make tabbing in editor behave properly

### ISSUE THREAD

**Issue by RichardJECooke** [rorywalsh/cabbage#46]
Pushing tab doesn't insert a tab as expected, it inserts 4 spaces. It would be great there was an option to use tabs or spaces as programmers are highly split about which they prefer.

But even if Cabbage can only use spaces then pushing backspace on a character after 4 spaces should move that character back 4 spaces, but it doesn't, it moves it back only 1, messing up alignment.

(Also, if you switch spaces per tab to 0 in the settings and try tab Cabbages crashes)

**Comment by rorywalsh** [comment]
I can add an option to insert tabs instead of spaces. But I'm not sure about backspace moving back four spaces. I agree it would be nice, but not something the JUCE editor currently supports.

**Comment by rorywalsh** [comment]
I added a way of using tabs instead of spaces. Use 0 for the number of spaces in the settings to force Cabbage to use tabs instead. The latest build is underway. You can grab it and test it from [here](https://dev.azure.com/rorywalsh/cabbage/_build?definitionId=1) once it's done.
