### ISSUE TITLE
Linux error during build

### ISSUE THREAD

**Issue by tank-trax** [rorywalsh/cabbage#49]
Unable to Build CabbageIDE

```
Building CabbageIDE…
Cleaning Cabbage
Compiling CabbageMainComponent.cpp
MakeCabbageIDE:174: recipe for target 'build/intermediate/Release/CabbageDocumentWindow_3af539ae.o' failed
make: *** [build/intermediate/Release/CabbageDocumentWindow_3af539ae.o] Error 1
make: *** Waiting for unfinished jobs....
Compiling FilterIOConfiguration.cpp
Compiling CabbageToolbarFactory.cpp
Compiling FilterGraph.cpp
```

CabbageLite builds

**Comment by tank-trax** [comment]
I got it to build. On Debian 9.9 seems like I need to run `python configureMakefiles.py` before `./buildCabbage`

**Comment by rorywalsh** [comment]
I was going to remove that script as it is no longer needed, but I guess
it's not a bad thing to leave it there!

**Comment by tank-trax** [comment]
this happens at the onset

```
./buildCabbage: line 15: [: ==: unary operator expected
JUCE v5.4.3
```

**Comment by rorywalsh** [comment]
I just push a change through to the Linux build script that should get around this issue until I have more time to investigate.

**Comment by tank-trax** [comment]
not sure if you changed something or if I did something wrong prior to posting this issue but I git cloned and ./buildCabbage completed with only this hitch at the end

```
g++ ../../Source/testCsoundFile.cpp -o testCsoundFile -I"/usr/local/include/csound" -lcsound64
/tmp/ccnLxQNS.o: In function `Csound::GetInputName()':
testCsoundFile.cpp:(.text._ZN6Csound12GetInputNameEv[_ZN6Csound12GetInputNameEv]+0x18): undefined reference to `csoundGetInputName'
collect2: error: ld returned 1 exit status

```

I think I was also mistakenly expecting everything to be in the LinuxMakefile/build/ folder but realized it's all there under LinuxMakefile/install/bin/

**Comment by rorywalsh** [comment]
I thought I had commented out that build step? Feel free to comment it out, it's not critical.
