### ISSUE TITLE
Virtual keyboard doesn't work on OSX unless -+rtmidi=null

### ISSUE THREAD

**Issue by kavika13** [rorywalsh/cabbage#5]
I have made a small plugin that reads from all midi devices and outputs midion2 to a specific device.

If I run without `-+rtmidi=null` (required to get the midi routing to work), then my real midi keyboard works, but the virtual midi keyboard isn't lighting up, or sending messages to the instrument.

If I run with `-+rtmidi=null` then none of the midi actually works, but then the virtual midi keyboard sends notes.

This is on today's latest download for OSX

**Comment by rorywalsh** [comment]
Are you using -M0 ?

**Comment by rorywalsh** [comment]
Hi @kavika13 any update on this?

**Comment by rorywalsh** [comment]
Closing this due to lack of a reply. You will need to pass `-M0 `along with `-+rtmidi=null`
