### ISSUE TITLE
[Request] Add bes instruments & effect as export options

### ISSUE THREAD

**Issue by Reaper10** [rorywalsh/cabbage#50]
I think would be great for cabbage to Add bes instrument & effect as export options.
BES is plugin format  for the Beast daw.
https://beast.testbit.org/
https://github.com/tim-janik/beast/

**Comment by rorywalsh** [comment]
Csound has a [LADSPA ](https://github.com/csound/csladspa)interface that can be used to host Csound instruments in BEAST. It works more or less the same as Cabbage. In fact, it is a precursor to Cabbage, it's more or less where the idea came from ;) It still ships with mot distributions of Csound but you'll need to try it out. More details can be found [here](http://csoundjournal.com/issue6/csLADSPA.html) Feel free to ask on the Cabbage forum, or here if you need any help.
