### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by gesellkammer** [rorywalsh/cabbage#56]
Trying to build in linux,

../../Source/GUIEditor/../LookAndFeel/CabbageLookAndFeel2.h:31:41: error: cannot convert ‘std::unique_ptr<juce::Drawable>’ to ‘juce::Drawable*’ in return
     return Drawable::createFromSVG (*xml);

**Comment by rorywalsh** [comment]
Can you try the latest dev tip? The latest version of JUCE breaks the master branch..

**Comment by gesellkammer** [comment]
Now this is failing:

Compiling include_juce_gui_extra.cpp
In file included from ../../JuceLibraryCode/include_juce_gui_extra.cpp:9:
../../JuceLibraryCode/modules/juce_gui_extra/juce_gui_extra.cpp:119:12: fatal error: gtk/gtk.h: No such file or directory
   #include <gtk/gtk.h>
            ^~~~~~~~~~~

**Comment by rorywalsh** [comment]
Have you installed webkit2gtk-4.0. My list of deps might not be up to date, [here's](https://forum.juce.com/t/list-of-juce-dependencies-under-linux/15121/29) what the JUCE guys say..

**Comment by gesellkammer** [comment]
I managed to build it now, thanks.

**Comment by rorywalsh** [comment]
Great. I'll close this out. There is a mention of the gtk stuff on the Linux build page, but it might need updating.
