### ISSUE TITLE
feature request: (computer) keyboard input

### ISSUE THREAD

**Issue by severak** [rorywalsh/cabbage#57]
some plugins (for example my own looper [Rebeat](https://forum.cabbageaudio.com/t/sampler-looper-and-starter/1693)) would greatly benefit in usability if there was a way how to manage them via computer keyboard. For example - looper is more likely started/stopped on time when doing it with keyboard.

It looks that this is definitely possible with JUCE - see [for example this](https://forum.juce.com/t/detecting-a-keypress/16441/3). 

I understand, that this will also open whole can of worms with compatibility with various OS/hosts, but I think it's worth of it.

I propose this API:

- there will be new reserved channels `LAST_KEY_PRESSED` and `LAST_KEY_RELEASED` which value would be code/name of last pressed key
- user can track changes via `changed:k(...)`
- host/OS incompatibilites are responsibitlity of plugin developers, not your ;-)

**Comment by rorywalsh** [comment]
I'm happy to take a look. But if you search for [keystrokes in host](https://forum.juce.com/search?q=keystroke%20in%20host) on the JUCE forum you see scores of questions on why it doesn't work in hosts, or at least it's prone to problems. On the other hand, many of those posts are old so perhaps the situation is better now.

**Comment by rorywalsh** [comment]
I've pushed through some code now that might help. 

**KEY_PRESSED** Returns the ASCII key code for the key currently being pressed
**KEY_DOWN** Returns 1 a key-down event, and 0 for a key-up event.  

It doesn't seem to be very straightforward to get the last released key using JUCE. Its key listener class only listens for the latest key pressed. It can probably be done, but I hope for now this is enough to help you out. I'm going to close this issue, but reopen it if you have any issues.
