### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by briansorahan** [rorywalsh/cabbage#58]
The download page says there is a README included in the zip file that has install instructions for Linux.
I have yet to locate said file.
What am I missing?

**Comment by briansorahan** [comment]
```
find . -name README
```

```
./JuceLibraryCode/modules/juce_graphics/image_formats/jpglib/README
./JuceLibraryCode/modules/juce_core/zip/zlib/README
./JuceLibraryCode/modules/juce_audio_formats/codecs/oggvorbis/libvorbis-1.3.2/README
```

This is what I see in the dir that unzip created ^

```
cat readme.md
```

```
![logo_cabbage_black_no_text](https://f.cloud.github.com/assets/5950903/1797870/31b2206e-6b15-11e3-9a9b-553c1c8edaad.png)

Cabbage. A framework for developing audio plugins and standalone instruments using the Csound programming language.
```

This has no install instructions ^

**Comment by rorywalsh** [comment]
Inside the Linux build folder, there is a README with instructions on building. 

https://github.com/rorywalsh/cabbage/tree/master/Builds/LinuxMakefile

I'll update the main page to make things a little clearer.

**Comment by briansorahan** [comment]
Thank you! I did end up finding the readme.md you're pointing to, but it would be great if we could update the docs too!
