### ISSUE TITLE
build fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by davephillips** [rorywalsh/cabbage#59]
Hey Rory,

I'm trying to build the Cabbage develop branch but I've hit a snag (see below). I'm using JUCE 5.4.7 and its modules, here's the error point: 

```
./buildCabbage
...
../../Source/Widgets/CabbageWidgetData.cpp: In static member function ‘static void CabbageWidgetData::setColourArrays(juce::StringArray, juce::ValueTree, juce::String, bool)’:
../../Source/Widgets/CabbageWidgetData.cpp:824:48: error: ‘juce::var::var(const void*)’ is private within this context
         newColours.append (new Colour (0, 0, 0));
                                                ^
In file included from ../../JuceLibraryCode/modules/juce_core/juce_core.h:276:0,
                 from ../../JuceLibraryCode/modules/juce_audio_basics/juce_audio_basics.h:53,
                 from ../../JuceLibraryCode/../JuceLibraryCode/JuceHeader.h:17,
                 from ../../Source/Widgets/../Utilities/CabbageUtilities.h:25,
                 from ../../Source/Widgets/CabbageWidgetData.h:24,
                 from ../../Source/Widgets/CabbageWidgetData.cpp:22:
../../JuceLibraryCode/modules/juce_core/containers/juce_Variant.h:322:5: note: declared private here
     var (const void*) = delete;
     ^~~
../../Source/Widgets/CabbageWidgetData.cpp:824:48: error: use of deleted function ‘juce::var::var(const void*)’
         newColours.append (new Colour (0, 0, 0));
                                                ^
```

I hope that helps, let me know if I'm missing anything obvious.

Best regards !

dp

**Comment by rorywalsh** [comment]
Thanks @davephillips  This is fixed in the dev branch. I'm still working on a few other things there before I merge. A simple fix is to append an empty string instead of a colour:

`newColours.append ("");`

**Comment by davephillips** [comment]
Thanks, Rory, I'll give it a whirl after exercises and coffee. :)

**Comment by davephillips** [comment]
@rorywalsh - Okay, the build completed after switching to the develop branch. Alas, all I have in the build folder is CabbageLite. I want CabbageHeavy, i.e. the entire enchilada. How do I get that ?

**Comment by rorywalsh** [comment]
Try the install folder.. that should contain all the heavies 🤣

**Comment by davephillips** [comment]
@rorywalsh - Install folder is where ? Incidentally, when I ran installCabbage I got this error:

```
./installCabbage 
install: cannot stat ‘./install/images/*’: No such file or directory
install: cannot stat ‘./install/bin/*’: No such file or directory
install: cannot stat ‘./install/desktop/*’: No such file or directory
cp: cannot stat ‘./install/Examples’: No such file or directory
cp: cannot stat ‘./install/Themes’: No such file or directory
```

Did I miss some steps somewhere ?

**Comment by rorywalsh** [comment]
I usually just run
./buildCabbage
sudo ./installCabbage

The buildCabbage script creates an install folder where everything gets
thrown for the install stage.

**Comment by davephillips** [comment]
Got it, thanks !
