### ISSUE TITLE
Cabbage Windows 10 installation issues with Csound

### ISSUE THREAD

**Issue by unfa** [rorywalsh/cabbage#60]
Hi!

I've installed Cabbage on Windows 10 today, and the fist thing it shown me was an error that it didn't find Csound libraries and failed to start. I have checked "Install Csound" during Setup wizard, so that was odd.

I have downloaded Csound for Windows and installed it afterwards.
It runs now, but I get a strange error message popping up twice every time I load a Cabbage plug-in in Ardour. After that it works fine, but I am worried it might cripple my work if I get 40 of these to click on every time I load an Ardour session using Cabbage plug-ins.

![image](https://user-images.githubusercontent.com/491704/76312223-d71ede00-62d2-11ea-8264-5d5cd673f04f.png)

This roughly translates into:

`Procedure entry point inflateValidate not found in library C:\Program Files\ Csound6_x64\plugins64\image.dll`

**Comment by rorywalsh** [comment]
Thanks for the translation ;) There is a problem with the current Windows version of Csound. Can you move the image.dll to a different folder and try again?

**Comment by unfa** [comment]
Ok, I've renamed the mentioned `image.dll` and the error masseges went away.

![image](https://user-images.githubusercontent.com/491704/76410817-e3697080-6390-11ea-972d-d17523b4072a.png)

Weird but I'm glad it works :D

**Comment by rorywalsh** [comment]
It's a static linking issue with that particular library. It needs zlib but
it's not found. The Csound devs are aware and are looking for a fix.
