### ISSUE TITLE
Convolution Rever(b) is named wrong

### ISSUE THREAD

**Issue by unfa** [rorywalsh/cabbage#61]
It's called "Convolution Rever".
Missing a "b" there.

**Comment by rorywalsh** [comment]
Thanks @unfa Is this with reference to a file name? Or a string in a file? Or?

**Comment by unfa** [comment]
No problem!
This is the name of the plug-in as listed in Ardour after exporting and installing it. I don't know where the error is, I am extremely new to Cabbage - I just wanted to use it's plugins for now.

**Comment by rorywalsh** [comment]
Ok. So there is actually a limit on the size of a plugin name, it's limited
to 16 chars. I can make it larger so others don't get caught out.

**Comment by unfa** [comment]
Ah, that's quite a short limit.
