### ISSUE TITLE
Archlinux (AUR) builds failing all the time 

### ISSUE THREAD

**Issue by sxiii** [rorywalsh/cabbage#62]
Greetings.

Cannot compile the cabbage from source. Tried using the cabbage-git package. Error related to JUCE_API PixelRGB class.

It would be nice if somebody could update the PKGBUILDs for archlinux.

Thanks

**Comment by rorywalsh** [comment]
Hi @sxiii I don't currently have an ARCH box to check this on. Can you post the errors you are getting? Can you also double check that you are using the latest master branch of JUCE? Note too that you will need the VST 2.4 SDK, which can be tricky to find these days. On the other hand, if you can install .deb packages on ARCH you can try one of the beta deb packages from [here](https://dev.azure.com/rorywalsh/cabbage/_build/results?buildId=623&view=artifacts&type=publishedArtifacts
). Just download the zip file, it'll be in there. It's still quite experimental. I don't think the desktop settings files is correct, but in my tests the main application and plugins interfaces installed fine. Let me know.

**Comment by danog** [comment]
This is now fixed, you can install the new cabbage-bin package.

**Comment by rorywalsh** [comment]
Great. Thanks for letting us know 👍

**Comment by sxiii** [comment]
Oh this is really nice, thanks @danog . Sorry I haven't contributed earlier to this :=) I will test the changes ASAP :)
