### ISSUE TITLE
Setting Cabbage root

### ISSUE THREAD

**Issue by ech2** [rorywalsh/cabbage#7]
I’m trying to make Cabbage run on Manjaro linux. Currently, Cabbage can’t find `CabbagePlugin.so` file and tells something about Cabbage root.

Here’s a screenshot of this error (Cabbage executable and the `*so` files are in the `CabbageBuild` folder):

![2018-03-23-115321_683x154_scrot](https://user-images.githubusercontent.com/1007225/37823193-6d81efa4-2e91-11e8-890a-3f5b57c7664c.png)

I looked up in the menu for an option to set the Cabbage root, but couldn’t find anything appropriate. Is there a way to hardcode it or maybe to set some environment variable to configure custom Cabbage root?

**Comment by rorywalsh** [comment]
Hi Eugene. Why is Cabbage trying to run from that directory? Are you running Cabbage from the CabbageBuild folder?

**Comment by ech2** [comment]
Hey Rory. OK, I checked the code (PluginExporter something cpp) and figured it out. Cabbage root seems to be the directory where the Cabbage executable is. That was a stupid mistake I have made while manually building Cabbage step by step. By some reason I had a plugin file named `CabbagePlugin.so` instead of `CabbagePluginSynth.so`. I’ll make a proper build for my distro…
