### ISSUE TITLE
Slowdown / lag with redrawing gentable widgets

### ISSUE THREAD

**Issue by tgrey1** [rorywalsh/cabbage#84]
There's been a lag introduced at some point in gentable widgets that redraw/refresh.

Examples include:
-  The SimpleTable example that's accessible from the Cabbage->Examples->Misc menu.
-  The SimpleADSR example I posted in this reply: https://forum.cabbageaudio.com/t/graphical-presentation-of-an-envelope/1840/7?u=t_grey

This was also briefly discussed in https://github.com/rorywalsh/cabbage/issues/81

**Comment by rorywalsh** [comment]
Thanks for filing this @tgrey1 You don't happen to know when it was introduced?

**Comment by tgrey1** [comment]
I have a bunch of installs dating back to march.  I tested them all, and they all failed.  I was completely baffled, because I **KNOW** I would have noticed since then...

That's when I noticed my march install still reported Cabbage 2.3.54... so I figured out it hasn't been overwriting the binary for some reason once again.  I'm taking a break for now, but I'll run through all of the old builds I still have and let you know roughly when it started happening.

**Comment by tgrey1** [comment]
Ok, I had to manually rm -rf the /Applications/Cabbage* directories to force clean them... the newest build I have that worked ok was downloaded 8.11.20 (2.3.53).  I didn't have a new build until 8.17.20 (2.3.54), which is when I noticed.

**Comment by awelex** [comment]
Turns out I introduced this while fixing a combobox bug. It's like whack-a-mole... I have a fix ready, just need to test first that it doesn't unfix the combobox bug.

**Comment by awelex** [comment]
fixed in PR #85

**Comment by tgrey1** [comment]
Tested the new build, looks much better.  Thanks!
