### ISSUE TITLE
Missing widget macros break parsing

### ISSUE THREAD

**Issue by tgrey1** [rorywalsh/cabbage#89]
It looks like if a widget line uses an undefined macro, the next entry of values on the line gets lost.

In this example, commenting out the color macro loses bounds() for one widget, and items() for the other!

``` csd
<Cabbage>
form caption("Combobox Example") size(400, 300), pluginID("test")

; commenting out the definition breaks things!
#define COLOR colour(255,0,0,255)

; this one loses it's items
combobox $COLOR items("1", "2", "3"), bounds(100, 100, 150, 30)

; this one loses it's bounds
combobox $COLOR bounds(100, 150, 150, 30), items("1", "2", "3")

</Cabbage>
<CsoundSynthesizer>
<CsOptions>
-n -d -+rtmidi=NULL -M0 -m0d 
</CsOptions>
<CsInstruments>
; Leave most value default, need something to compile
ksmps = 32

</CsInstruments>
<CsScore>
;causes Csound to run for about 7000 years...
f0 z
</CsScore>
</CsoundSynthesizer>
```
This is how it looks by default:
![image](https://user-images.githubusercontent.com/8214623/92008790-98179580-ed15-11ea-87f0-82ec41c833f1.png)

And then if you comment out the color macro, which should in theory *ONLY* lose the color settings for the widgets, it looks like this:
![image](https://user-images.githubusercontent.com/8214623/92008825-a5348480-ed15-11ea-805b-8858ea025b15.png)

**Comment by rorywalsh** [comment]
Using the very latest build, 2.3.56, I don't see any issues? 

![macroTest](https://user-images.githubusercontent.com/2689817/92024952-c4073b00-ed56-11ea-843d-ec19494bd33d.gif)

**Comment by tgrey1** [comment]
Oi, let me freshen up.  I think I'm on an Aug.20 build.

I had an Aug.24 build, but for some reason I stepped back... I don't recall why.  Maybe https://github.com/rorywalsh/cabbage/issues/83?

**Comment by tgrey1** [comment]
Hrm... I grabbed 20200902.2, and this example still appears to break for me in both full and lite.

**Comment by tgrey1** [comment]
Ok... this is interesting.  It matters on if it's commented out like:
`;#define COLOR colour(255,0,0,255)`
vs.
`; #define COLOR colour(255,0,0,255)`

![image](https://user-images.githubusercontent.com/8214623/92036076-b2656980-ed3d-11ea-8d21-bdb242b4dd27.png)

![image](https://user-images.githubusercontent.com/8214623/92036108-bdb89500-ed3d-11ea-9caa-574c5004f96a.png)

**Comment by rorywalsh** [comment]
Interesting! I'll take a deeper look tomorrow..

**Comment by rorywalsh** [comment]
Should be fixed now in git. Note that I only tested this case, so you might want to quickly run through some other macro heavy .csd files just to make sure my commit doesn't break them. Can you close this out if it passes your tests? Thanks.

**Comment by rorywalsh** [comment]
Ha, I was afraid of something like that! I had another go at fixing it. Let me know if it works. Both of your csd run fine.

**Comment by tgrey1** [comment]
20200903.4 is looking much better!  I ran some of my most macro heavy examples, and everything appears to be working exactly as expected.

I'll close this out and reopen if needed, or open a new one if it seems more appropriate to whatever I find.  Thanks for taking a look at this!
