### ISSUE TITLE
Exported effect plugins are recognized as VSTi and doesn’t process sound

### ISSUE THREAD

**Issue by ech2** [rorywalsh/cabbage#9]
Hei Rory. At the moment on my system (Manjaro) Cabbage doesn’t create proper VST effects. After exporting an effect plugin (e.g. LoFi) to the VST format, Reaper (native Linux build) shows it as VSTi, and the plugin just passes sound through without doing any processing. Exporting VSTi works fine though.

Have you had such issues before? I can provide more info if needed.

This is a script I used to build Cabbage with: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cabbage-git

**Comment by rorywalsh** [comment]
I've not seen this issue before. Is it the same in other hosts?

**Comment by ech2** [comment]
Yes, it is. Well, at least in Renoise.

**Comment by rorywalsh** [comment]
I'll look into when I get back Eugene. The build script might be slightly messed up maybe but I never noticed before..

**Comment by rorywalsh** [comment]
Hi @ech2 sorry for taking so long to get this done but it should be working fine now again. Can you check with the last tip and let me know?

**Comment by ech2** [comment]
Thanks! I’ll check everything soon. Lol, the diff for this issue: https://github.com/rorywalsh/cabbage/commit/dc6e8a5258c72ff4c2b9d5e648c75b87de0b268a — I could’ve guessed!

**Comment by rorywalsh** [comment]
I know! Piff 🙄

**Comment by ech2** [comment]
I checked, it works fine now! Thanks!
