### ISSUE TITLE
MacOS Catalina compile error "Reference to 'Point' is ambiguous"

### ISSUE THREAD

**Issue by andy-fillebrown** [rorywalsh/cabbage#92]
I am getting a "Reference to 'Point' is ambiguous" compile error on MacOS Catalina when building with Juce 5.4.7. Is anybody else hitting this?

The solution is to change all uses of `Point` to `juce::Point` but I don't want to do that if I'm the only one hitting the error.

Is anyone building on MacOS Catalina and can reproduce this error? I'm seeing some people reporting it at https://forum.juce.com/t/reference-to-point-is-ambiguous/24884/9 but nobody has reported it here, yet, so I'm curious. Am  I the only one building on MacOS Catalina?

**Comment by rorywalsh** [comment]
I'm still on high sierra, so yeah, you might be the only one building on
Catalina..?

**Comment by andy-fillebrown** [comment]
I made a PR #93 to fix it. It shouldn't cause any issues for other platforms.
